### PR TITLE
Unit tests and remove IDE folers/files

### PR DESCRIPTION
**Pull request by rysiekblah**
Hey Kevin,
UT added, and also I removed all IDE staff like target and *iml files and also .idea folder.

Tomasz

### CODE REVIEW

**Comment by rysiekblah** [comment]
hei it look there are merge conflicts

**Comment by kevincantstop** [comment]
np at all i will fix it later i should invite you to the main branch

**Comment by rysiekblah** [comment]
yeah, this is better, then pull requests way

**Comment by kevincantstop** [comment]
ok try it again

**Comment by kevincantstop** [comment]
why don't you logon to skype?

**Pull request merged**
